[package]
name = "opusfile"
version = "0.1.0"
authors = ["matze"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opusfile-sys = { path = "../opusfile-sys" }
enum_primitive = "0.1.1"